### ISSUE TITLE
this issue is in order to show respect to mr đạt tạ's skills

### ISSUE THREAD

**Issue by Tathai2412** [tathanhdatt/Java-Basics#1]
code rất hay và dễ hiểu, câu từ chỉnh chu, phông chữ rất đẹp. 10 điểm :)))

**Comment by tathanhdatt** [comment]
ok:)

**Comment by tathanhdatt** [comment]
> code rất hay và dễ hiểu, câu từ chỉnh chu, phông chữ rất đẹp. 10 điểm :)))

ok:)

**Comment by Lawliet529** [comment]
How is this an issue???
